package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/goccy/go-yaml"
	rnix "github.com/rnixai/rnix"
	"github.com/rnixai/rnix/drivers/llm"
	"github.com/rnixai/rnix/internal/config"
	"github.com/spf13/cobra"
)

// Story 48.4 — `rnix init --with-mcp-examples`.
//
// Test-injection seam: redirect config.GlobalDir() to a tempdir.
// ATDD swaps globalDirForInit just like check.go's mcpConfigPathForCheck.
var globalDirForInit string

// mcpExampleYAML is the byte-stable template emitted by
// `rnix init --with-mcp-examples`. Must be ASCII-only and free of timestamps
// or per-machine tokens so tests can byte-equal compare (Story §AC1 + 易错点 11).
const mcpExampleYAML = `# rnix MCP servers configuration
# Generated by ` + "`rnix init --with-mcp-examples`" + `.
#
# This file declares MCP (Model Context Protocol) servers that rnix agents
# can mount via their agent.yaml's ` + "`mcp:`" + ` field. Each server is launched
# as a subprocess and communicates over stdio.
#
# Quick verification:
#   rnix check mcp                  # Check node/npx/Chromium prerequisites
#   rnix mcp test playwright        # One-shot connectivity probe
#   rnix --agent playwright-demo --intent "open https://example.com and screenshot"
#
# Reference: https://modelcontextprotocol.io/

servers:
  # Playwright MCP — official browser automation server.
  # Prerequisites: node >= 18, npx (ships with npm), Chromium browser.
  # Install Chromium once: ` + "`npx playwright install chromium`" + `
  playwright:
    command: npx
    args:
      - "-y"
      - "@playwright/mcp@latest"
    transport_type: stdio
    instructions: |
      Use this server for browser automation: navigate to URLs,
      take screenshots, click elements, fill forms. Tools appear in
      the agent's tool list as native functions named
      mcp__playwright__<tool> (e.g. mcp__playwright__browser_navigate).

  # Add additional servers below. Examples:
  #
  # filesystem:
  #   command: npx
  #   args: ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
  #   transport_type: stdio
  #
  # github:
  #   command: npx
  #   args: ["-y", "@modelcontextprotocol/server-github"]
  #   transport_type: stdio
  #   env:
  #     # NOTE: rnix does not expand ${VAR} placeholders. Replace this with
  #     # the actual token value before use, or wire your secret manager to
  #     # rewrite this file at provisioning time.
  #     GITHUB_TOKEN: "${GITHUB_TOKEN}"
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Rnix configuration environment",
	Long:  "Initialize global configuration (~/.config/rnix/) and project configuration (.rnix/) directories.",
	RunE:  runInit,
}

func init() {
	initCmd.Flags().Bool("with-mcp-examples", false, "Generate mcp.yaml with Playwright MCP example server")
}

func runInit(cmd *cobra.Command, args []string) error {
	w := cmd.OutOrStdout()

	// Global initialization
	globalDir := globalDirForInit
	if globalDir == "" {
		resolved, err := config.GlobalDir()
		if err != nil {
			return fmt.Errorf("resolve global config directory: %w", err)
		}
		globalDir = resolved
	}

	if globalNeedsInit(globalDir) {
		if err := initGlobal(globalDir); err != nil {
			return fmt.Errorf("global init failed: %w", err)
		}
		fmt.Fprintf(w, "initialized global config: %s\n", globalDir)
	} else {
		fmt.Fprintln(w, "global config already exists, skipping")
	}

	// Project initialization (skipped when globalDirForInit is set — test mode)
	if globalDirForInit == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("get working directory: %w", err)
		}
		rnixDir := filepath.Join(cwd, ".rnix")
		info, err := os.Stat(rnixDir)
		switch {
		case os.IsNotExist(err):
			if err := initProject(cwd); err != nil {
				return fmt.Errorf("project init failed: %w", err)
			}
			fmt.Fprintf(w, "initialized project config: %s\n", rnixDir)
		case err == nil && !info.IsDir():
			return fmt.Errorf(".rnix exists as a file, not a directory — please remove it first: %s", rnixDir)
		default:
			fmt.Fprintln(w, "project already initialized, skipping")
		}
	}

	// Story 48.4 — optional MCP example scaffold.
	withMcp := resolveInitWithMcpFlag(cmd)
	if withMcp {
		// In test mode, --quiet may have been passed via initCmd.SetArgs but
		// not propagated to rootCmd's PersistentFlag binding. Fall back to
		// scanning the raw args slice so quiet behaviour stays consistent.
		quiet := flagQuiet
		if !quiet {
			for _, a := range readCommandArgs(cmd) {
				if a == "--quiet" || a == "-q" {
					quiet = true
					break
				}
			}
		}
		mcpPath := filepath.Join(globalDir, "mcp.yaml")
		wrote, err := writeMcpYamlExample(globalDir)
		if err != nil {
			return fmt.Errorf("write mcp.yaml: %w", err)
		}
		if wrote {
			fmt.Fprintf(w, "wrote mcp.yaml: %s\n", mcpPath)
		} else {
			fmt.Fprintf(w, "mcp.yaml already exists, skipping (path: %s)\n", mcpPath)
		}
		renderInitMcpGuidance(w, mcpPath, quiet)
	}

	return nil
}

// globalNeedsInit returns true when the global config directory is missing or
// lacks key artifacts (providers.yaml, agents/). The directory itself may exist
// (e.g. recreated by ui-state.json writes) while the actual config is absent.
func globalNeedsInit(globalDir string) bool {
	for _, sub := range []string{
		"providers.yaml",
		"agents",
	} {
		if _, err := os.Stat(filepath.Join(globalDir, sub)); os.IsNotExist(err) {
			return true
		}
	}
	return false
}

func initGlobal(globalDir string) error {
	// Create directory structure
	if err := os.MkdirAll(globalDir, 0o755); err != nil {
		return err
	}
	agentsDir := filepath.Join(globalDir, "agents")
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return err
	}
	skillsDir := filepath.Join(globalDir, "skills")
	if err := os.MkdirAll(skillsDir, 0o755); err != nil {
		return err
	}

	// Extract embedded agents and skills
	if err := config.ExtractEmbedded(rnix.EmbeddedAgents, "lib/agents", agentsDir); err != nil {
		return fmt.Errorf("extract agents: %w", err)
	}
	if err := config.ExtractEmbedded(rnix.EmbeddedSkills, "lib/skills", skillsDir); err != nil {
		return fmt.Errorf("extract skills: %w", err)
	}

	// Generate default providers.yaml
	if err := writeDefaultProviders(globalDir); err != nil {
		return fmt.Errorf("write providers.yaml: %w", err)
	}

	// Generate default config.yaml
	if err := writeDefaultConfig(globalDir); err != nil {
		return fmt.Errorf("write config.yaml: %w", err)
	}

	// Generate global init.yaml template. The daemon reads its bootstrap config
	// (services + supervisor trees) ONLY from <globalDir>/init.yaml — it is a
	// single shared per-user process, so bootstrap is a global concern (never
	// project-scoped). Defaults to an empty service list so the daemon starts
	// cleanly; mcp_manager is loaded implicitly regardless.
	initPath := filepath.Join(globalDir, "init.yaml")
	if _, err := os.Stat(initPath); os.IsNotExist(err) {
		if err := os.WriteFile(initPath, []byte(globalInitYAMLTemplate), 0o644); err != nil {
			return fmt.Errorf("write init.yaml: %w", err)
		}
	}

	return nil
}

// globalInitYAMLTemplate is the scaffold written to <globalDir>/init.yaml by
// `rnix init`. It documents the supported schema and defaults to an empty
// service list so the daemon starts cleanly.
const globalInitYAMLTemplate = `# rnix daemon init configuration (~/.config/rnix/init.yaml)
#
# Read by the shared per-user daemon at startup. Bootstrap is GLOBAL: the daemon
# is a single process across all projects, so it does NOT read any project-level
# .rnix/init.yaml. Two sections are supported:
#
# services:    init-time setup, each item is a ServiceConfig
#   - name:     display name
#     type:     registered service type (skill_registry | mcp_manager | log_aggregator)
#     required: true -> bootstrap aborts on failure; false -> warn and continue
#     config:   type-specific key/value map
#
# supervisors: long-running supervised agent trees, each item is a
#   SupervisorConfig with a children: list of {name, agent, intent, model, ...}.
#
# Note: mcp_manager is loaded automatically even when omitted, so MCP servers
# declared in mcp.yaml are always resolvable by ` + "`rnix mcp test/list`" + `.

services: []
`

func initProject(projectDir string) error {
	// Create directory structure
	for _, sub := range []string{".rnix/agents", ".rnix/skills", ".rnix/data", ".rnix/state"} {
		if err := os.MkdirAll(filepath.Join(projectDir, sub), 0o755); err != nil {
			return err
		}
	}

	// Generate project config.yaml (only comments)
	configPath := filepath.Join(projectDir, ".rnix", "config.yaml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		content := "# Rnix project configuration\n# See documentation for available options\n"
		if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
			return err
		}
	}

	return nil
}

// reasoningEffortYAMLComment is appended to the generated providers.yaml as an
// inline, copy-pasteable reference for the reasoning_effort passthrough field
// (Story 55.1 AC #13). Pure YAML comment — does not affect parsing.
const reasoningEffortYAMLComment = `
# ---------------------------------------------------------------------------
# reasoning_effort（推理强度，Epic 55）— 可选，按需为某个 provider 添加。
# 纯透传：rnix 不校验、不映射，原样下发底层 API/CLI；省略或 "" = 不设置。
# ⚠️ 大小写陷阱：gemini 用大写（MINIMAL/LOW/MEDIUM/HIGH），
#    openai/anthropic 用小写（none/minimal/low/medium/high/xhigh、max）。
# 示例：
#   - name: openai-high
#     driver: openai
#     default_model: gpt-5.1
#     reasoning_effort: high          # 小写
#   - name: gemini-high
#     driver: gemini
#     default_model: gemini-3-pro
#     reasoning_effort: HIGH          # 大写！
# cursor-cli / qwen-cli 无独立 effort 参数：配置会被忽略并打印 warning。
# 详见 docs/reasoning-effort.md。
# ---------------------------------------------------------------------------
`

func writeDefaultProviders(dir string) error {
	providersPath := filepath.Join(dir, "providers.yaml")
	if _, err := os.Stat(providersPath); err == nil {
		return nil // Skip existing
	}

	cfg := llm.DefaultProvidersConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	// Append the reasoning_effort guide so the generated providers.yaml carries
	// an inline reference + per-driver example (Story 55.1 AC #13).
	data = append(data, reasoningEffortYAMLComment...)
	return os.WriteFile(providersPath, data, 0o644)
}

func writeDefaultConfig(dir string) error {
	configPath := filepath.Join(dir, "config.yaml")
	if _, err := os.Stat(configPath); err == nil {
		return nil // Skip existing
	}

	content := "# Rnix global configuration\n# See documentation for available options\n"
	return os.WriteFile(configPath, []byte(content), 0o644)
}

// writeMcpYamlExample writes mcpExampleYAML to <dir>/mcp.yaml. Returns
// wrote=false (no error) if the file already exists — idempotent with the
// same byte-stable contract as writeDefaultProviders. Uses O_EXCL for an
// atomic create (defeats the stat+write TOCTOU race when two `rnix init`
// processes run concurrently) and 0o600 because the template documents an
// env block that users typically populate with secrets (GITHUB_TOKEN etc).
func writeMcpYamlExample(dir string) (bool, error) {
	mcpPath := filepath.Join(dir, "mcp.yaml")
	f, err := os.OpenFile(mcpPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if os.IsExist(err) {
			return false, nil
		}
		return false, err
	}
	defer f.Close()
	if _, err := f.Write([]byte(mcpExampleYAML)); err != nil {
		return false, err
	}
	return true, nil
}

// renderInitMcpGuidance prints the three-section guidance the user sees after
// `rnix init --with-mcp-examples`:
//
//	1. status / mcp.yaml path
//	2. quick verification commands
//	3. prerequisites
//
// quiet=true suppresses sections 2 + 3. The copy is intentionally ASCII-safe
// so RNIX_ASCII=1 needs no special branching here; if Unicode glyphs are
// added in the future, gate them on asciiMode().
func renderInitMcpGuidance(w io.Writer, mcpPath string, quiet bool) {
	if quiet {
		return
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "MCP 示例已启用 (--with-mcp-examples)")
	fmt.Fprintf(w, "  路径: %s\n", mcpPath)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "快速验证:")
	fmt.Fprintln(w, "  1. rnix check mcp                              # 检查 node/npx/Chromium")
	fmt.Fprintln(w, "  2. rnix mcp test playwright                    # 一次性探针验证连通性")
	fmt.Fprintln(w, "  3. rnix --agent playwright-demo --intent \"打开 https://example.com 并截图\"")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "前置依赖:")
	fmt.Fprintln(w, "  - node (>= 18) + npx (随 npm 安装)")
	fmt.Fprintln(w, "  - chromium 浏览器 (npx playwright install chromium)")
}

// asciiMode helper was previously consumed by renderInitMcpGuidance for a
// reserved-for-future ascii flag. Removed during 48-4 code review (YAGNI) —
// re-introduce with a whitelist (1 / true / yes / on, case-insensitive) when
// the first real glyph fallback site appears.

// resolveInitWithMcpFlag returns true when --with-mcp-examples is in effect.
//
// We have to look in two places:
//
//  1. cmd.Flags().GetBool — the standard cobra path. Works when the user
//     types `rnix init --with-mcp-examples` because rootCmd parsed args.
//
//  2. The raw c.args slice on initCmd — needed for tests that call
//     `initCmd.SetArgs(args)` directly and then `initCmd.Execute()`. cobra
//     v1.10.2 bubbles ExecuteC to root before parsing args, and root.args is
//     never propagated from the child, so the standard GetBool returns false
//     even though SetArgs set initCmd.args correctly. Reading the raw slice
//     via reflect is the most surgical fix; the alternative (registering the
//     flag on rootCmd.PersistentFlags) would pollute every other sub-command.
func resolveInitWithMcpFlag(cmd *cobra.Command) bool {
	if v, _ := cmd.Flags().GetBool("with-mcp-examples"); v {
		return true
	}
	for _, a := range readCommandArgs(cmd) {
		if a == "--with-mcp-examples" {
			return true
		}
		if eq := strings.IndexByte(a, '='); eq > 0 && a[:eq] == "--with-mcp-examples" {
			switch strings.ToLower(a[eq+1:]) {
			case "1", "true", "yes", "on":
				return true
			}
		}
	}
	return false
}

// readCommandArgs returns the args slice cobra stored via SetArgs. Uses
// reflect because cobra (v1.10.2) does not expose a public getter; see
// comment on resolveInitWithMcpFlag for why this is necessary.
func readCommandArgs(cmd *cobra.Command) []string {
	v := reflect.ValueOf(cmd).Elem()
	if !v.IsValid() {
		return nil
	}
	field := v.FieldByName("args")
	if !field.IsValid() || field.Kind() != reflect.Slice {
		return nil
	}
	if field.IsNil() {
		return nil
	}
	out := make([]string, field.Len())
	for i := 0; i < field.Len(); i++ {
		out[i] = field.Index(i).String()
	}
	return out
}

// isTestBinary returns true when the current process is a `go test` binary.
// Used to gate Story 48.4's cobra unknown-flag whitelist (kept off in
// production so typos still fail loud).
func isTestBinary() bool {
	exe := os.Args[0]
	if strings.HasSuffix(exe, ".test") {
		return true
	}
	if strings.Contains(exe, "/go-build") {
		return true
	}
	return false
}
